---
# DEPENDENCIES ###################################################
- name: Update packages
  tags: apt,dependencies
  apt:
    update_cache: yes

- name: Upgrade packages
  tags: apt,dependencies
  apt:
    name: "*"
    state: latest

- name: Install packages
  tags: apt,dependencies
  apt:
    pkg:
    - acl
    - git
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - software-properties-common
    - sudo
    - nano
    - jq
    - cmake
    - lnav
    - make
    - glances
    - python3
    - python3-pip
    - docker
    - docker.io

- name: Download docker-compose
  tags: dependencies
  shell: 'curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose'
  args:
    warn: false
    
# USERS ##########################################################
- name: Create sysadmins group
  tags: accounts
  group:
    name: sysadmins

- name: Add system administrators
  tags: accounts
  user:
    name: "{{ item.name }}"
    groups: sysadmins
    shell: "{{ item.shell | default('/bin/bash') }}"
    append: yes
  loop: "{{ accounts }}"

- name: Install authorized_keys for accounts
  tags: accounts
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', item.key) }}"
  loop: "{{ accounts }}"
  when: not ansible_check_mode

- name: Setup sudo for system administrators
  copy:
    content: '%sysadmins ALL=(ALL) NOPASSWD: ALL'
    dest: /etc/sudoers.d/sysadmins

# DATA ###########################################################
- name: Create directory for web data
  tags: data
  file:
    path: /var/www/html
    state: directory

- name: Download popultion data
  tags: data
  shell: 'curl -L "https://www.webcodesign.de/population/" -o /var/www/html/population.json'
  args:
    warn: false

- name: Clone Coronavirus Tracker API
  tags: data
  git:
    repo: "{{ api_repo }}"
    dest: /usr/local/src/coronavirus-tracker-api

# DOCKER #########################################################
- name: Stop any running docker-compose
  tags: docker
  shell: 'docker-compose down'
  args:
    chdir: /usr/local/src/coronavirus-tracker-api/

- name: Start Docker service
  tags: docker
  service:
    name: docker
    state: started

- name: Switch to another branch of the Coronavirus Tracker API
  tags: docker
  git:
    repo: "{{ api_repo }}"
    dest: /usr/local/src/coronavirus-tracker-api
    clone: no
    update: no
    version: "{{ api_branch }}"

- name: Run docker-compose
  tags: docker
  shell: 'docker-compose up -d'
  args:
    chdir: /usr/local/src/coronavirus-tracker-api/
